### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by Dr-bioinfo** [bcgsc/NanoSim#190]
I'm getting this issue while running the chimeric and quantification arguments for metagenome mode 

**ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.**

**Comment by SaberHQ** [comment]
Would you please provide more information regarding your experiment? What parameters you are using? Are you training a new model or using pre-trained models?

My best guess based on the error is that it looks like there is no reference genome selected or it couldn't read your file.

**Comment by Dr-bioinfo** [comment]
Hello ,
I am working with the pre-trained models and encountering an error while using the -c and -q parameters in characterization stage

**Comment by Dr-bioinfo** [comment]
Also, I am encountering one more issue while using your tool, specifically the latest release, NanoSim 3.1.0. I have observed that it hangs during the simulation stage and does not complete its work. Despite allowing ample time for execution, the tool does not provide any output or progress indication.

**Comment by SaberHQ** [comment]
> Also, I am encountering one more issue while using your tool, specifically the latest release, NanoSim 3.1.0. I have observed that it hangs during the simulation stage and does not complete its work. Despite allowing ample time for execution, the tool does not provide any output or progress indication.

This might be related to the issue reported here: #184 
Pull request #189 should fix that. It is now merged into the master branch. Make sure to use the latest committed version and see if it solves the issue.

**Comment by Dr-bioinfo** [comment]
Yeah!! I tried with improved code too. But the issue still permits

**Comment by kmnip** [comment]
> ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

Can you please report your exact command and your TSV file for `--genome_list`?

> Also, I am encountering one more issue while using your tool, specifically the latest release, NanoSim 3.1.0. I have observed that it hangs during the simulation stage and does not complete its work. Despite allowing ample time for execution, the tool does not provide any output or progress indication.

How did you run the updated code?
